version: "3.7"

services:

  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    volumes:
      - ./frontend/src:/code/frontend/src
      - ./frontend/public:/code/frontend/public
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8080

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8080:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=@r*&z!0xi#*-t80h0n+w3%4rqr7i(*f6(5k#1vjz70dfp7h^vt
      - DB_HOST=host.docker.internal
      - DB_NAME=portfolio
      - DB_USER=portfoliouser
      - DB_PASSWORD=Password@123
      - DB_PORT=5432
      - CACHE_LOCATION=redis://127.0.0.1:6379/1
    depends_on:
      - redis

  redis:
    image: redis:alpine