version: "3.7"

services:

  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    volumes:
      - ./frontend/src:/code/frontend/src
      - ./frontend/public:/code/frontend/public
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine

  engine:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.engine
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - backend
      - redis
