FROM python:3.9
ENV PYTHONUNBUFFERED=1

#backend dependecies
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/

CMD ["celery", "-A", "portfolio", "worker", "-l", "INFO"]
