# Generated by Django 4.1 on 2022-09-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetClassesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("decimal_places", models.IntegerField()),
            ],
            options={
                "db_table": "asset_classes",
            },
        ),
        migrations.CreateModel(
            name="AssetsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.CharField(max_length=128)),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investment_tracker.assetclassesmodel",
                    ),
                ),
            ],
            options={
                "db_table": "assets",
            },
        ),
        migrations.CreateModel(
            name="CountriesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "countries",
            },
        ),
        migrations.CreateModel(
            name="TransactionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supply_value", models.BigIntegerField()),
                ("receive_value", models.BigIntegerField()),
                ("created_at", models.DateTimeField()),
                ("knowledge_begin_date", models.DateTimeField()),
                ("knowledge_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "receive_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_with_received",
                        to="investment_tracker.assetsmodel",
                    ),
                ),
                (
                    "supply_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_with_supplied",
                        to="investment_tracker.assetsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
        migrations.AddField(
            model_name="assetsmodel",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investment_tracker.countriesmodel",
            ),
        ),
    ]
