# Generated by Django 4.1 on 2023-02-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetClassesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("decimal_places", models.IntegerField()),
            ],
            options={
                "db_table": "asset_classes",
            },
        ),
        migrations.CreateModel(
            name="AssetsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("ticker", models.CharField(max_length=128)),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investment_tracker.assetclassesmodel",
                    ),
                ),
            ],
            options={
                "db_table": "assets",
            },
        ),
        migrations.CreateModel(
            name="AsyncTasksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=128,
                    ),
                ),
                ("percentage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "async_tasks",
            },
        ),
        migrations.CreateModel(
            name="CountriesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "countries",
            },
        ),
        migrations.CreateModel(
            name="TransactionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supply_value", models.CharField(max_length=50)),
                ("supply_base_conv_rate", models.CharField(max_length=50)),
                ("receive_value", models.CharField(max_length=50)),
                ("receive_base_conv_rate", models.CharField(max_length=50)),
                ("transacted_at", models.DateTimeField()),
                (
                    "receive_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_with_received",
                        to="investment_tracker.assetsmodel",
                    ),
                ),
                (
                    "supply_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_with_supplied",
                        to="investment_tracker.assetsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="HoldingsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("average_buy", models.CharField(max_length=50)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investment_tracker.assetsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "holdings",
            },
        ),
        migrations.AddField(
            model_name="assetsmodel",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investment_tracker.countriesmodel",
            ),
        ),
    ]
