# Generated by Django 4.1 on 2022-10-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionsmodel",
            old_name="created_at",
            new_name="transacted_at",
        ),
        migrations.RemoveField(
            model_name="transactionsmodel",
            name="knowledge_begin_date",
        ),
        migrations.RemoveField(
            model_name="transactionsmodel",
            name="knowledge_end_date",
        ),
    ]
