# Generated by Django 4.1 on 2022-12-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investment_tracker",
            "0002_rename_created_at_transactionsmodel_transacted_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetsmodel",
            old_name="origin",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="assetsmodel",
            old_name="identity",
            new_name="ticker",
        ),
        migrations.AddField(
            model_name="assetsmodel",
            name="name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
