# Generated by Django 4.1 on 2023-02-20 04:06
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0003_conversionratesmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversionratesmodel",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
