# Generated by Django 4.1 on 2023-01-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0003_rename_origin_assetsmodel_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionsmodel",
            name="receive_value",
            field=models.DecimalField(decimal_places=18, max_digits=34),
        ),
        migrations.AlterField(
            model_name="transactionsmodel",
            name="supply_value",
            field=models.DecimalField(decimal_places=18, max_digits=34),
        ),
    ]
