# Generated by Django 4.1 on 2023-01-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0004_alter_transactionsmodel_receive_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionsmodel",
            name="receive_value",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transactionsmodel",
            name="supply_value",
            field=models.BigIntegerField(),
        ),
    ]
