# Generated by Django 4.1 on 2023-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0005_alter_transactionsmodel_receive_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncTasksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN-PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=128,
                    ),
                ),
                ("percentage", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "async_tasks",
            },
        ),
    ]
