# Generated by Django 4.1 on 2023-01-31 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0006_asynctasksmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="asynctasksmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 1, 31, 18, 19, 35, 683381, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asynctasksmodel",
            name="ended_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="asynctasksmodel",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
