# Generated by Django 3.2.17 on 2023-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracker', '0007_asynctasksmodel_created_at_asynctasksmodel_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctasksmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
