# Generated by Django 4.1 on 2023-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0008_alter_asynctasksmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynctasksmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                max_length=128,
            ),
        ),
    ]
