# Generated by Django 4.1 on 2023-02-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0009_alter_asynctasksmodel_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionsmodel",
            name="receive_value",
        ),
        migrations.RemoveField(
            model_name="transactionsmodel",
            name="supply_value",
        ),
    ]
