# Generated by Django 4.1 on 2023-02-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0010_remove_transactionsmodel_receive_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionsmodel",
            name="receive_value",
            field=models.CharField(default="0x0", max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactionsmodel",
            name="supply_value",
            field=models.CharField(default="0x0", max_length=36),
            preserve_default=False,
        ),
    ]
