# Generated by Django 4.1 on 2023-02-14 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0011_transactionsmodel_receive_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=36)),
                ("date", models.DateTimeField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investment_tracker.assetsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "holdings",
            },
        ),
    ]
