# Generated by Django 4.1 on 2023-02-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_tracker", "0012_holdingsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionsmodel",
            name="receive_base_conv_rate",
            field=models.CharField(default="0", max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactionsmodel",
            name="supply_base_conv_rate",
            field=models.CharField(default="0", max_length=36),
            preserve_default=False,
        ),
    ]
